### PR TITLE
Allow Agents have Agent children

### PR DESCRIPTION
**Pull request by Flood1993**
Rough first implementation of allowing Agent objects to have other Agent objects as children.

Simple usage file: [example.txt](https://github.com/opensistemas-hub/osbrain/files/885289/example.txt)

Note that it needs to be run with `$ python -O ...` so as to disable assertions.

Random thoughts/comments about this:
 - Having to disable assertions might be problematic. Perhaps we should add to the documentation some tips about how this could be achieved and warning of possible downsides, but without officially being part of osBrain?
 - Shutting down an agent, as of now, will wait until of of its children are shutdown.
 - In case we decided to implement this officially, care should be taken when shutting down a child agent by hand, and not through its parent.
 - As of now, Agent is the only class allowed for children.

### CODE REVIEW

**Comment by one4many** [comment]
I tried it with a remote nameserver. It it seems the nsaddr and addr addresses are not inherited by the child. A monkey patch adding (the nameserer addr) to the create_child_agent function 

```
 def create_child_agent(self, name, nsaddr=None, addr=None):
        assert False, 'Assertions must be disabled for child agents!'

        if not hasattr(self, '_sub_agents'):
            self._sub_agents = []

        sub_agent = run_agent(name=name, nsaddr=nsaddr, addr=addr)
        self._sub_agents.append(ChildrenData(sub_agent, name))
        return sub_agent
```
seemed to work but ultimately ended in another exception:
```
Traceback (most recent call last):
  File "regNewBot.py", line 12, in <module>
    log = herder.create_child_agent('testChild1', nsaddr)
  File "/home/alex/anaconda3/lib/python3.5/site-packages/Pyro4/core.py", line 171, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/alex/osbtest/bot/osbrain_child/osbrain/proxy.py", line 159, in _pyroInvoke
    methodname, args, kwargs, flags, objectId)
  File "/home/alex/osbtest/bot/osbrain_child/osbrain/proxy.py", line 204, in _remote_call
    flags=flags, objectId=objectId)
  File "/home/alex/anaconda3/lib/python3.5/site-packages/Pyro4/core.py", line 426, in _pyroInvoke
    raise data
ValueError: too many values to unpack (expected 8)
```

**Comment by Flood1993** [comment]
I have made some minor improvements so as to get more control over the child agents when creating them (same functionality as in a raw `run_agent()` call.

**Comment by one4many** [comment]
Here is the 'client' code:

```
from osbrain_child.osbrain import run_agent
from osbrain_child.osbrain.proxy import NSProxy, locate_ns

nsaddr = locate_ns('127.0.0.1:28282')
ns = NSProxy(nsaddr)
herder = ns.proxy('BotHerder')
log = herder.create_child_agent('ChildAgent1', nsaddr)
log.setup(3, 4, herder)
```

Here is the 'server' code:
```
from osbrain_child.osbrain import run_agent, Agent
from osbrain_child.osbrain.proxy import NSProxy, locate_ns
import osbrain_child.osbrain as osbrain
osbrain.Pyro4.config.SERVERTYPE = 'thread'

def print_data(agent, data):
    print(data)

class MyOtherClass():
    def __init__(self, a,b):
        self.data = a+b

    def dosomething(self):
        return(self.data)

class MyAgent(Agent):
    def __init__(self, name, host=None, serializer=None, transport=None):
        Agent.__init__(self, name=None, host=None, serializer=None, transport=None)
        self.d = None

    def on_init(self):
        self.bind('PUB', alias='pAPI')

    def setup(self, a, b, herder):
        self.d = MyOtherClass(a,b)
        self.herder = herder
        self.herder.send('pAPI', self.d.dosometing())
        return True

def main():
    botHerder = run_agent('BotHerder', '127.0.0.1:28282', '127.0.0.1', base=MyAgent)
    testAgent = run_agent('APItest', '127.0.0.1:28282')
    testAgent.connect(botHerder.addr('pAPI'), handler=print_data)

if '__main__' in __name__:
    main()
```

Here is the nameserver code:
```
from osbrain import run_nameserver
import time

if __name__ == '__main__':
    ns = run_nameserver('127.0.0.1:28282')
    while True:
        for alias in ns.agents():
            print (alias)
        time.sleep(5)
```

Running all 3 py scripts result in the error above.

**Comment by one4many** [comment]
Any updates? I have a hard stop on my project here because of this (missing) feature.

**Comment by Flood1993** [comment]
Closing this PR in favor of #112 .

I will leave my branch open for reference. A new issue will probably be created for discussing the internal implementation for subagents (if any). 

Unfortunately I haven't had time to look more into it, since I'm a bit busy lately.

**Pull request closed without merging**
