### PR TITLE
Test safe calls on non-running agents

### PR DESCRIPTION
**Pull request by Peque**
While reviewing #158 found a piece of code in `agent.py` that was not covered and fixing it was very simple...

### CODE REVIEW

**Comment by Flood1993** [comment]
Test not fully covered 😄 . Maybe add a call to ``my_name()`` before raising the exception?

**Comment by Peque** [comment]
@Flood1993 Yeah, already fixed, I think. Travis will have the last word. :-P

**Comment by Peque** [comment]
"very simple" :joy:

**Comment by Peque** [comment]
Seems like one test failed with: https://travis-ci.org/opensistemas-hub/osbrain/jobs/300138642

Updated #210 as it is probably related.

**Pull request merged**
