### PR TITLE
Add first SIGINT test to an agent (not the NameSever agent)

### PR DESCRIPTION
**Pull request by Flood1993**
Added first test related to SIGINTs. As for the first commit, only an agent which is not the NameServer is tested.

In relation to #20

### CODE REVIEW

**Comment by Flood1993** [comment]
Tests are not passing beacuse the teardown is not being done correctly in `test_sigint_no_handling`.

However, I think this is how it should behave as of now. Perhaps we could close #20 and open a new issue with the suggestion of 2-step interruption, while leaving this PR open?

**Comment by Flood1993** [comment]
I have been working on implementing #60 , but it is not done yet. Even though I got all the tests to pass once through `tox -e py35` on commit ff7ed4b , there is something I'm still missing.

I think it is related to the different ways there are for terminating an agent. I also wonder if there is a better way for handling the signals than counting them.

**Comment by Flood1993** [comment]
Despite passing all tests with the four Python versions tested by Travis CI in this repository, in my fork the CI build failed, more precisely, the Python 3.3 version. Relevant parts are pasted below.

It seems the `test_sigint_agent_shutdown` is the most problematic. Without the `time.sleep`s, every try has failed.

```[gw4] FAILED osbrain/tests/test_agent.py::test_sigint_agent_shutdown 
...
=================================== FAILURES ===================================
__________________________ test_sigint_agent_shutdown __________________________
[gw4] linux -- Python 3.3.5 /home/travis/build/Flood1993/osbrain/.tox/py33/bin/python3.3
nsaddr = 127.0.0.1:18932
    def test_sigint_agent_shutdown(nsaddr):
        """
        Test SIGINT (simulation) signal on a non NameServer agent.
    
        A single signal is sent: we want the agent to shut down gracefully.
        Two seconds are given to give enough time to free the resources.
        """
        class NewAgent(Agent):
            def simulate_SIGINT(self):
                os.kill(os.getpid(), signal.SIGINT)
    
        ns = NSProxy(nsaddr)
    
        # Test SIGINT on an Agent based on the new class
        AgentProcess('new', nsaddr=nsaddr, base=NewAgent).start()
        new = Proxy('new', nsaddr)
        new.run()
        assert 'new' in ns.list()
        assert new.ping() == 'pong'
        new.simulate_SIGINT()
        time.sleep(2)
        with pytest.raises(Exception):
            assert new.ping() == 'pong'
>       assert 'new' not in ns.list()
E       assert 'new' not in {'Pyro.NameServer': 'PYRO:Pyro.NameServer@127.0.0.1:18932', 'new': 'PYRO:obj_59072630f42e4d8e8acb6bbf7143164f@localhost:36653'}
E        +  where {'Pyro.NameServer': 'PYRO:Pyro.NameServer@127.0.0.1:18932', 'new': 'PYRO:obj_59072630f42e4d8e8acb6bbf7143164f@localhost:36653'} = <Pyro4.core._RemoteMethod object at 0x7f643fc03710>()
E        +    where <Pyro4.core._RemoteMethod object at 0x7f643fc03710> = <osbrain.proxy.NSProxy at 0x7f643fc0ea50; connected; for PYRONAME:Pyro.NameServer@127.0.0.1:18932>.list
osbrain/tests/test_agent.py:101: AssertionError
==================== 1 failed, 236 passed in 33.32 seconds =====================
ERROR: InvocationError: '/home/travis/build/Flood1993/osbrain/.tox/py33/bin/pytest --basetemp=/home/travis/build/Flood1993/osbrain/.tox/py33/tmp --cache-clear -n 8 -sv --pep8 --flakes --mccabe --cov --boxed'
___________________________________ summary ____________________________________
ERROR:   py33: commands failed
The command "tox" exited with 1.
fter_script.1
3.51s$ pip install codecov coveralls
Collecting codecov
  Downloading codecov-2.0.5-py2.py3-none-any.whl
Collecting coveralls
  Downloading coveralls-1.1-py2.py3-none-any.whl
Collecting requests>=2.0.0 (from codecov)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting coverage (from codecov)
  Downloading coverage-4.3.4.tar.gz (361kB)
    100% |################################| 364kB 1.6MB/s 
Collecting argparse (from codecov)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Collecting docopt>=0.6.1 (from coveralls)
  Downloading docopt-0.6.2.tar.gz
Installing collected packages: docopt, argparse, coverage, requests, coveralls, codecov
  Running setup.py install for docopt
  Running setup.py install for coverage
    building 'coverage.tracer' extension
    gcc -pthread -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -I/opt/python/3.3.5/include/python3.3m -c coverage/ctracer/datastack.c -o build/temp.linux-x86_64-3.3/coverage/ctracer/datastack.o
    gcc -pthread -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -I/opt/python/3.3.5/include/python3.3m -c coverage/ctracer/filedisp.c -o build/temp.linux-x86_64-3.3/coverage/ctracer/filedisp.o
    gcc -pthread -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -I/opt/python/3.3.5/include/python3.3m -c coverage/ctracer/module.c -o build/temp.linux-x86_64-3.3/coverage/ctracer/module.o
    gcc -pthread -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -I/opt/python/3.3.5/include/python3.3m -c coverage/ctracer/tracer.c -o build/temp.linux-x86_64-3.3/coverage/ctracer/tracer.o
    gcc -pthread -shared -L/opt/python/3.3.5/lib -Wl,-rpath=/opt/python/3.3.5/lib build/temp.linux-x86_64-3.3/coverage/ctracer/datastack.o build/temp.linux-x86_64-3.3/coverage/ctracer/filedisp.o build/temp.linux-x86_64-3.3/coverage/ctracer/module.o build/temp.linux-x86_64-3.3/coverage/ctracer/tracer.o -L/opt/python/3.3.5/lib -lpython3.3m -o build/lib.linux-x86_64-3.3/coverage/tracer.cpython-33m.so
    Installing coverage script to /home/travis/virtualenv/python3.3.5/bin
    Installing coverage-3.3 script to /home/travis/virtualenv/python3.3.5/bin
    Installing coverage3 script to /home/travis/virtualenv/python3.3.5/bin
Successfully installed argparse-1.4.0 codecov-2.0.5 coverage-4.3.4 coveralls-1.1 docopt-0.6.2 requests-2.13.0
after_script.2
1.43s$ codecov
      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.5
==> Detecting CI provider
    Travis Detected
==> Preparing upload
==> Processing gcov (disable by -X gcov)
    Executing gcov (find /home/travis/build/Flood1993/osbrain -type f -name '*.gcno'  -exec gcov -pb  {} +)
==> Collecting reports
    Generating coverage xml reports for Python
    + /home/travis/build/Flood1993/osbrain/coverage.xml bytes=38602
==> Appending environment variables
    + TRAVIS_OS_NAME
    + TRAVIS_PYTHON_NAME
==> Uploading
    .url https://codecov.io
    .query job=208524068&pr=false&branch=sigint_tests&package=py2.0.5&slug=Flood1993%2Fosbrain&service=travis&commit=a8ba637239f66f6ebebf4fcf192dd1cd196ab5a9&build=8.4
    Pinging Codecov...
    Uploading to S3...
    https://codecov.io/github/Flood1993/osbrain/commit/a8ba637239f66f6ebebf4fcf192dd1cd196ab5a9
after_script.3
0.61s$ coveralls
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
Done. Your build exited with 1.```

**Comment by Peque** [comment]
@Flood1993 save your current `pip freeze`. Then try to `pip install --upgrade -r requirements.txt`. If it works after that, then either forget about it or (better) "debug" until you get which package version upgrade made things work again.

**Comment by Flood1993** [comment]
As of 8032599 , the only SIGINT we are handling with the `_sigint_handler` is the first one, and the others are handled by the default Python handler (treated as `KeyboardInterrupt`). 

I also have added some tests for checking that processes are really getting killed when they should. However, the tests are failing for detecting alive threads. Right now we are reading the `/proc` directory to find the PID's of the processes on the system, and checking against each PID of our agents/nameserver. However, apart from not currently working, this only works on Linux based systems.

**Comment by ocaballeror** [comment]
Integrated into #249

**Pull request closed without merging**
