### PR TITLE
Fix PyZMQ 17 compatibility issues

### LINKED ISSUE #303: Update PyZMQ to version 17
As pointed in #302, it doesn't work right now, so we should probably find a way to properly use the new version, rather than avoiding it forever.

Might be a PyZMQ issue. Reference: https://github.com/zeromq/pyzmq/issues/1170.

See also: https://github.com/zeromq/libzmq/issues/3204

### PR DESCRIPTION
**Pull request by Peque**
By manually cleaning IPC files after closing sockets.

Fixes #303. Closes #305.

### CODE REVIEW

**Comment by ocaballeror** [comment]
Is this not the same as #305 ?

**Comment by Peque** [comment]
@ocaballeror Almost. Only we unlink from the binder only and we make sure we close all sockets in a channel. I do not mind implementing this over #305 if you think it is better (to keep @minrk's contribution in the history).

**Comment by Peque** [comment]
@ocaballeror Yeah, did not want to bother him with rebasing, squashing or commit message style rules, but I guess we can be more lenient when accepting external/occasional contributions. :blush:

I'll do the rebase/squash/rename while keeping his authorship and then add the current changes as a "refactor". :+1:

**Comment by Peque** [comment]
@ocaballeror Done.

**Pull request merged**
